spring:

  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  sql.init.mode: NEVER
  flyway:
    enabled: true
server:
  port: 8282

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE